### ISSUE TITLE
Non-python user trying to run the software

### ISSUE THREAD

**Issue by LFIKidwell** [ltalirz/sycofinder#2]
I am a MOF chemist with very little programming experience. I have attempted to run the python script locally. The error message says I need to run it in a production environment. Sadly this is where I get stuck.

My attempts at running it in a docker container are even less successful.

Please could you provide more detail on how to get this script to run for a complete novice?

**Comment by ltalirz** [comment]
Hi @LFIKidwell, this is what you should see when running it locally:

```
$ python run.py
/Users/leopold/.local/lib/python3.6/site-packages/jupyter_client/session.py:56: VisibleDeprecationWarning:

zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.


Running on http://0.0.0.0:8050/
Debugger PIN: 737-173-349
 * Serving Flask app "sycofinder" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
/Users/leopold/.local/lib/python3.6/site-packages/jupyter_client/session.py:56: VisibleDeprecationWarning:

zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.


Running on http://0.0.0.0:8050/
Debugger PIN: 214-547-515
```
Then you'll need to open `http://0.0.0.0:8050/` in your web browser

if your output differs from this, please provide it

**Comment by ltalirz** [comment]
by the way, I just realized that there was no link to the live version from the github repo.
I guess you want to modify the code - if not just click on the link in the readme

**Comment by LFIKidwell** [comment]
Ah thank you, I didn't realise that I was looking at a link in the Readme!

Seems to be working fine, thank you!
